### ISSUE TITLE
`@psalm-assert =T $actual` causes uncaught Psalm\Exception\TypeParseTreeException: Unexpected token = 

### ISSUE THREAD

**Issue by TysonAndre** [psalm/phpunit-psalm-plugin#1]
1. The annotation should be fixed in stubs/Assert.php
2. Psalm should be changed to warn but not crash

**Comment by muglug** [comment]
I think this is fixed? Psalm was updated around the same time (but this isn't released yet, so it'll have a couple of teething problems)

**Comment by muglug** [comment]
This was the fix: https://github.com/vimeo/psalm/commit/08d99402598ea8a35b2d6fc2e6453e3d0897a0eb

Though this was broken (and thus broke Psalm's build because it used the third arg) until I added the message arg in https://github.com/psalm/phpunit-psalm-plugin/commit/6a387da8e2f7fda6cd6c6ebe990be49bdb1b7e1d

**Comment by muglug** [comment]
For future reference, I decided to change `^` to `=` because I think the latter makes more sense in documentation (and the 3.x change gave an opportunity for a break, in case anyone was using `@psalm-assert ^MyClass`
